# Generated by Django 4.2 on 2023-04-10 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0004_customer_username_alter_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='productlist',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='SubscriptionList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='office.customer')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='office.productlist')),
            ],
        ),
    ]
