# Generated by Django 4.2 on 2023-04-10 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0005_productlist_price_subscriptionlist'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='subscriptionlist',
            constraint=models.UniqueConstraint(fields=('customer_id', 'product_id'), name='unique_customer_product_subscription'),
        ),
    ]
