# Generated by Django 4.2 on 2023-04-10 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0007_productlist_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverylist',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='deliverylist',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddConstraint(
            model_name='deliverylist',
            constraint=models.UniqueConstraint(fields=('deliveryperson', 'customer'), name='unique_deliveryperson_customer_deliverylist'),
        ),
    ]
