# Generated by Django 4.2 on 2023-04-11 07:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0010_user_salary'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='subscriptionlist',
            name='unique_customer_product_subscription',
        ),
        migrations.RenameField(
            model_name='subscriptionlist',
            old_name='customer_id',
            new_name='customer',
        ),
        migrations.RenameField(
            model_name='subscriptionlist',
            old_name='product_id',
            new_name='product',
        ),
        migrations.AlterField(
            model_name='user',
            name='deliveries',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='salary',
            field=models.FloatField(default=0),
        ),
        migrations.AddConstraint(
            model_name='subscriptionlist',
            constraint=models.UniqueConstraint(fields=('customer', 'product'), name='unique_customer_product_subscription'),
        ),
        migrations.AddField(
            model_name='bill',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='office.customer'),
        ),
        migrations.AddField(
            model_name='bill',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='office.productlist'),
        ),
        migrations.AddConstraint(
            model_name='bill',
            constraint=models.UniqueConstraint(fields=('customer', 'product'), name='unique_customer_product_bill'),
        ),
    ]
