# Generated by Django 4.2 on 2023-04-11 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0011_bill_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='due_days',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customer',
            name='pause',
            field=models.BooleanField(default=False),
        ),
    ]
