# Generated by Django 4.2 on 2023-04-10 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0002_customer_productlist_alter_user_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.IntegerField(choices=[(0, 0), (1, 1)], default=0),
        ),
    ]
