# Generated by Django 4.2 on 2023-04-11 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0008_deliverylist_completed_alter_deliverylist_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='deliveries',
            field=models.IntegerField(null=True),
        ),
        migrations.DeleteModel(
            name='Deliveries',
        ),
    ]
